# EPS400/522
#### Computational Methods for Geoscience - Fall 2023
#### Instructor: Eric Lindsey
---------
<b> Adrian Marziliano </b>
<br> Aug 22, 2023

# Assignments for Lab 1

This notebook contains some assignments (or puzzles) you should try to solve to improve your understanding of python and make sure you understood the things you read in the examples notebook. Some of them are harder than others, don't feel bad if the solution seems unreachable or confusing! This is all part of the learning process. If you are stuck, feel free to ask your neighbor, the instructors, google, or even a Chat AI for help. 

It's OK if you don't get through everything. The last assignments especially are designed to challenge you, and if they feel overwhelming now, try coming back to them in a couple days - you may be surprised how much you've learned!

This assignment will not be graded and you don't need to turn it in (unless you want to)!

### 0. Bug Assignment:

In [1]:
This cell has two bugs. First run it to see the error message, then try to fix the bugs one at a time.

prnt("I have fixed the bugs!")

SyntaxError: invalid syntax (3674265522.py, line 1)

The two bugs were:
1. The instructions were not 'commented' out with a '#' so the code cell tried to read this as Python code
2. The 'print' command was mispelled as 'prnt' and was not recognized as 'print'

In [2]:
#This cell has two bugs. First run it to see the error message, then try to fix the bugs one at a time.

print("I have fixed the bugs!")

I have fixed the bugs!


### 1. Variables assignment: radians/degrees
Create a variable called "deg2rad" that will convert degrees into radians whenever you multiply it by a value in degrees. For example, we want this to work correctly for any value `number_in_degrees`:

    number_in_radians = number_in_degrees * deg2rad

Test your work by demonstrating that 180 degrees is equal to pi radians.

Then compute 1 degree in radians, and 1 radian in degrees.

Hint: radians = degrees * pi / 180 

Second hint: to use a more exact value of "pi", you have to import numpy as np. Then you can use "np.pi"


In [3]:
# Convert degress to radians (TEST)
deg2rad = 0.0174533
num_deg = 180

num_rad = num_deg * deg2rad
print ("This is a test!", num_deg, "degrees is equal to", num_rad, "radians.")

This is a test! 180 degrees is equal to 3.1415940000000004 radians.


In [4]:
# Convert degress to radians
deg2rad = 0.0174533
num_deg = 1

num_rad = num_deg * deg2rad
print (num_deg, "degrees is equal to", num_rad, "radians.")

1 degrees is equal to 0.0174533 radians.


In [5]:
# Convert radians to degrees
num_rad = 1

num_deg = num_rad/deg2rad
print (num_rad, "radians is", num_deg, "degrees")

1 radians is 57.29575495751519 degrees


### 2. Numbers assignment
Write a function that will calculate the time that a signal takes to reach us from a GPS satellite, given the speed of light is roughly 2.99 x 10^8 meters/second. The altitude of the GPS satellite above the surface of Earth is 20,000 kilometers. 

You have the following tasks:

(a) Define a variable for the speed of light, using scientific notation. In python this is done with 'e'. For example, `4.34e5` is equal to 434,000


In [6]:
# speed of light [m/s]
c = 2.99e8

(b) Define a variable for the altitude of the GPS satellite, in meters, also using scientific notation (be careful of units here!)

 

In [7]:
# Altitude of satellite [km]
alt = 434000

 (c) Use the formula Time = Distance/Velocity, to calculate the time required by the signal to reach the Earth from the GPS satellite Assign the result to a new variable and print out the result.



In [8]:
# T=D/V
# units = m/(m/s) = seconds
T = (alt*1000)/c
print (T, "seconds")

1.451505016722408 seconds


### 3. String assignment: 
Using the altitude and travel-time variables you calculated in part 2 above, print out the time traveled by the signal as a nicely formatted sentence:

    The time taken by the signal from a GPS satellite at an altitude of XXXX km to reach the Earth is X.XXXXX seconds.

  TIP: to print a variable using print() use the following syntax, where %f is the place-holder for a floating point variable, given with %variable at the end of the line:


      print ('the variable value is %f' %value) 
      
You can use other formatting options: %s for strings, and %d for integers. If you want to include more than one variable, you can list them in parentheses:


      print ('the first value is %f, the second is %d' %(value1,value2)) 
      
Finally, for floating point values you can control the number of values after the decimal point with e.g. "%.2f" for 2 decimal values.

Note, this is only one way of generating nicely formatted strings. Check out this page for (much) more information if you are interested: https://realpython.com/python-string-formatting/

In [9]:
print ('The time taken by the signal from a GPS satellite at an altitude of %.0f kilometers to reach earth is %.2f seconds.' %(alt,T))

The time taken by the signal from a GPS satellite at an altitude of 434000 kilometers to reach earth is 1.45 seconds.


### 4. Expression assignment
Define a variable, then create an expression that determines whether one computation done with that variable is larger than or smaller than another one. Your expression should return either "True" or "False" and save that value to a new variable. Then print out both the value and the type of that variable.

In [10]:
a = 2
y = 2*a > 1/a
print(y, type(y))

True <class 'bool'>


### 5. List assignment: 

a. Add 'kiwi' to the following list, before 'cherry', and print out the result

In [11]:
thislist = ["apple", "banana", "cherry"]
thislist

['apple', 'banana', 'cherry']

In [12]:
#thislist.append("kiwi")
thislist.insert(2, "kiwi")
print(thislist)

['apple', 'banana', 'kiwi', 'cherry']


b. Create a list containing days of the week (starting with Sunday). Write a statement that indexes this list given an integer from 1 to 7 (defined as a variable "dayNum"), and prints out that day of the week. Note that if dayNum=1, your statement should print out Sunday - you will have to deal with the zero-indexing issue of Python!

In [13]:
dayNum = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
dayNum[1:7] = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
print(dayNum[1])

Sunday


### 6. Array assignment: Create a 3x3 array, and print out only the middle column.

In [14]:
#thisarray = [[0,1],[2,3]]
array = [['a','b','c'],['1','2','3'],['d','e','f']]
print (array[1])

['1', '2', '3']


### 7. Conditionals assignment:
Create a 2x2 numpy array, then compare the [0,0] and [1,1] elements of the array, and give a message about which is larger.

In [15]:
import numpy as np
np_array = np.array([[1,2],[3,4]])

if np_array[0,0]>np_array[1,1]:
    print('[0,0] is greater than [1,1]')
else:
    print('[1,1] is greater than [0,0]')

[1,1] is greater than [0,0]


### 8. Loops assignment:
a. Create a nested for loop (two for loops inside each other) that populate the values of a 5x5 numpy array with the product of the two array index values. E.g:

    myarray[i,j] = i*j
    
Hint: we will first need to create a blank array of size 5x5. To do this, we use the following syntax:

    myarray=np.zeros((5,5))

In [16]:
import numpy as np

# Create blank array
myarray = np.zeros((5, 5), dtype=int)
#myarray

# Two nested loops to populate array
for i in range(5):
    for j in range(5):
        myarray[i, j] = i * j

print(myarray)

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]


b. Use a while loop to keep rolling a dice, and only stop when you roll a 6. To roll a dice from 1 to 6 in python, we can use:

    a = np.random.randint(1,7)

**Warning**: When trying out while loops, user beware! If you cause a bug that makes it run forever, use the square "stop" button at the top of the page. Occasionally it may crash your jupyter page.

**Note**: It's a good idea to use more informative variable names. Instead of calling your dice roll "a", give it a more informative name. This is a good habit to get into early on!

In [17]:
# Roll the dice (6 sided dice)

while True:
    a = np.random.randint(1, 7)
    
    print(f'You rolled a: {a}')
    
    if a == 6:
        print('The game is over!')
        break

You rolled a: 1
You rolled a: 5
You rolled a: 4
You rolled a: 2
You rolled a: 2
You rolled a: 4
You rolled a: 5
You rolled a: 1
You rolled a: 1
You rolled a: 3
You rolled a: 6
The game is over!


### 9. Functions assignment: 
With all you've learned so far, you are now able to write some more or less fully-fledged programs! Here are a few exercises to practice your function mastery. For each one, give the function a sensible name, and test it with a few different inputs to make sure it works as you expect. 

a. Write a function that accepts 2 inputs: a string, and a number. The function should use a loop to print out the input string the specified number of times. Then call the function, using your name and favorite number as the input

In [18]:
# Two user input simple function
def two_input():
    input1 = input("Type your favourite colour: ")
    input2 = int(input("Now input your favourite number: "))
    
    print("Your favourite colour is", input1,"and your favourite number is", input2, ".")

# Call function
two_input()

Type your favourite colour:  blue
Now input your favourite number:  2


Your favourite colour is blue and your favourite number is 2 .


In [19]:
# User input function with loop
def input_loop():
    while True:
        user_input = input("Day something (type 'exit' to quit): ")
        
        if user_input.lower() == 'exit':
            print("Exiting the loop.")
            break
        else:
            print(f"You entered: {user_input}")

# Call the function to start the input loop
input_loop()

Day something (type 'exit' to quit):  Hello


You entered: Hello


Day something (type 'exit' to quit):  exit


Exiting the loop.


In [34]:
def input_loop():
    while True:
        user_input1 = input("Type your favourite food: ")
        user_input2 = input("Input a number between 0 and 20: ")
        
        print(f"Congratulations! You just won {user_input2} {user_input1}s!")

        user_input3 = input("Exit?")
        if user_input3.lower() == 'yes':
            print("Exiting the loop")
            break
            
# Call the function to start the input loop
input_loop()

Type your favourite food:  pizza
Input a number between 0 and 20:  15


Congratulations! You just won 15 pizzas!


Exit? yes


Exiting the loop


b. Convert your answer to question 1 above into a function called "deg2rad" that will convert any number input in degrees to radians


In [35]:
# Degree to radians conversion function
def deg2rad():
    deg_input = int(input("Input a number in degrees: "))
    deg2rad = 0.0174533
    rad = deg_input * deg2rad
    
    print("Your input of", deg_input, "degrees converts to", rad, "radians.")

# Call function
deg2rad()

Input a number in degrees:  24


Your input of 24 degrees converts to 0.4188792 radians.


c. Write a function that will convert geographic coordinates in degree (D), minute (M), second (S) to decimal degrees format (DMS to DD.DDDD)
    
      Hint: 1 minute = 1/60 degree, 1 second = 1/3600  degree

In [37]:
# Geographic coordinate converstion function
# DMS to DD conversion
def DMS_to_DD():
    D_input = int(input("This program will convert DMS coordinates to decimal degrees. Enter coordinate degree (D): "))
    M_input = int(input("Enter coordinate minute (M): "))
    S_input = int(input("Enter coordinate second (S): "))
    
    DD_output = D_input + M_input/60 + S_input/3600
    print("Your DMS coordinates convert to", DD_output, "in decimal degrees.")

# Call function
DMS_to_DD()

This program will convert DMS coordinates to decimal degrees. Enter coordinate degree (D):  56
Enter coordinate minute (M):  23
Enter coordinate second (S):  6


Your DMS coordinates convert to 56.385 in decimal degrees.


d. (Complicated!) Write a function that will input year, month, day and output day of year (the so-called "Julian date")

   Tricky: beware of leap years, which are any years that can be exactly divided by 4, but not by 100 - i.e. 2004 is a leap year but 2000 is not.
   
   Hint: Python has a 'modulo' division symbol (%) that gives the remainder of division; this can tell you if a number is exactly divisible: for example, try 2015 % 4, and 2016 % 4
   

In [41]:
def Julian_day(year, month, day):
    """
    Convert a date (year, month, day) to the Julian day of the year (ordinal date).
    
    Parameters:
        year (int): The year (e.g., 2023).
        month (int): The month (1-12).
        day (int): The day of the month (1-31).
    
    Returns:
        int: The Julian day of the year.
    """
    input_year = int(input("Input year"))
    input_month = int(input("Input month number"))
    input_day = int(input("Input day number"))
    
    # Check for valid month and day values
    if not (1 <= month <= 12) or not (1 <= day <= 31):
        raise ValueError("Invalid month or day")

    # Number of days in each month
    days_in_month = [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

    # Check for leap year and update February
    if year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):
        days_in_month[2] = 29

    # Calculate the Julian day
    Julian_day = sum(days_in_month[:month]) + day

    return Julian_day

# Example usage:
#year = 2023
#month = 9
#day = 14
Julian_day = Julian_day(year, month, day)
print(f"The Julian day for the date {year}-{month:02d}-{day:02d} is {Julian_day}")


Input year 2023
Input month number 9
Input day number 14


The Julian day for the date 2023-09-14 is 257


e. Optional: Re-do problem d, but using the built-in python module 'datetime'. Use google to find the manual for the datetime module. You may find the code is much shorter!

In [39]:
from datetime import datetime

# Function converts a date to the Julian day of the year.
def Julian_day2(year, month, day):
 
    date_obj = datetime(year, month, day)
    Julian_day = date_obj.timetuple().tm_yday
    return Julian_day

# Call function:
year = 2023
month = 9
day = 14
Julian_day = Julian_day2(year, month, day)
print(f"The Julian day for {year}-{month:02d}-{day:02d} is {Julian_day}")


The Julian day for 2023-09-14 is 257


### 10. Optional Assignment: modules

Make a module that contains a function that computes distance on a sphere by implementing one of the distance algorithms from https://en.wikipedia.org/wiki/Great-circle_distance.

Then import the module here, and compute the distance between Albuquerque (Lon, Lat: -106.62, 35.08) and your dream vacation destination.


### 11. Optional Assignment: programming challenges!
Try a programming challenge from 
https://www.codecademy.com/resources/blog/python-code-challenges-for-beginners/, or https://pythonprinciples.com/challenges/.